parameters:
#    json_schema.example.class: HadesArchitect\JsonSchemaBundle\Example

services:
#    json_schema.example:
#        class: %json_schema.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
